### ISSUE TITLE
Crash on WSL (Windows subsystem for linux) Ubuntu machine.

### ISSUE THREAD

**Issue by Consti10** [HD-Fpv/Open.HD_Image_Builder#14]
Here is my console output :;

Error: /home/consti/Open.HD_Image_Builder/work/01-Baseimage/IMAGE.img: unrecognised disk label
ROOT OFFSET:

Welcome to fdisk (util-linux 2.31.1).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.

Device does not contain a recognized partition table.
Created a new DOS disklabel with disk identifier 0xa008c635.

Command (m for help): No partition is defined yet!
Could not delete partition 139897463754521

Command (m for help): 2: unknown command

Command (m for help): Partition type
   p   primary (0 primary, 0 extended, 4 free)
   e   extended (container for logical partitions)
Select (default p): Partition number (1-4, default 1): First sector (2048-4194303, default 2048): Last sector, +sectors or +size{K,M,G,T,P} (2048-4194303, default 4194303):
Created a new partition 2 of type 'Linux' and of size 2 GiB.

Command (m for help): The partition table has been altered.
Syncing disks.

/home/consti/Open.HD_Image_Builder/stages/01-Baseimage /home/consti/Open.HD_Image_Builder
[11:11:50] End /home/consti/Open.HD_Image_Builder/stages/01-Baseimage/01-run.sh
[11:11:50] End /home/consti/Open.HD_Image_Builder/stages/01-Baseimage
[11:11:50] Begin /home/consti/Open.HD_Image_Builder/stages/02-Kernel
Kernel not configured for semaphores (System V IPC). Not using udev synchronisation code.
losetup: failed to parse offset: '': Invalid argument

**Comment by RespawnDespair** [comment]
@Consti10 You talked about unzip missing? Was this the case?
It appears the base image was not downloaded or extracted...

**Comment by Consti10** [comment]
unzip wasn't installed on my machine - adding it to the 'required packages' certainly won't hurt.
But even after installing unzip, the routine breaks at the same point - fdisk cannot partition properly or something.

I am installing Ubuntu on Oracle VM VirtualBox now.

**Comment by careyer** [comment]
You might want to consider downloading a ready-to-use VM from here: https://www.osboxes.org/ :-)

**Comment by pilotnbr1** [comment]
closing...
