### ISSUE TITLE
No video transmitted

### ISSUE THREAD

**Issue by htcohio** [HD-Fpv/Open.HD_Image_Builder#2]
Problem with air pi video TX error after WFB>>Open.hd name label and code merging. 

Telemetry and RC seem to work fine.

**Comment by Yes21** [comment]
Video was working with the image I did build yesterday after the code merging.
Perhaps a problem with the work in progress in the refactory branch ?

**Comment by pilotnbr1** [comment]
Thats weird that it was working.. I think the only change I made to the master branch is to add what appears to be the missing python psutils library.

Has anyone tried it now with the library added back in? I cant try now.. will try tomorrow

**Comment by Yes21** [comment]
I don't understand this problem with psutils.
This library has never been present in @RespawnDespair and @user1321 repos (I've just checked them right now).
And I've never had this issue "No video transmitted" with master branch of yesterday and today, and I can't reproduce it.

**Comment by Yes21** [comment]
psutil should be installed from python-psutil before I added "no-install-recommends" in 03-Packages/00-run-chroot.sh.
After reverting this, video transmission is working again.
The "sudo pip install psutil" added by Luke shouldn't be usefull anymore.
So I removed it ...
