### ISSUE TITLE
How to use with fork of original repository

### ISSUE THREAD

**Issue by Consti10** [HD-Fpv/Open.HD_Image_Builder#26]
Answering the question myself:
int `stages/04-Wifibroadcast/00-run.sh` replace

`sudo git clone https://github.com/HD-Fpv/Open.HD.git`

with

`sudo git clone https://github.com/<YOUR USERNAME>/Open.HD.git `
e.g. `https://github.com/Consti10/Open.HD.git`

**Comment by pilotnbr1** [comment]
closing
