### ISSUE TITLE
Default hotspot recommended change from "g" to "a" 

### ISSUE THREAD

**Issue by htcohio** [HD-Fpv/Open.HD_Image_Builder#4]
Most imagebuilder images have "g" channel "1" set instead of "a" channel xx (36 is the first, probably best default"

Reason:

Open.hd is best utilized and recommended to be used with RPI 3b+ because of dual band (g or a) hotspot.

A majority of users use 2.4ghz for video so it is probably best to have default hotspot set to 5ghz.

**Comment by Yes21** [comment]
Ok I will set it to a and 36.

**Comment by Yes21** [comment]
Corrected
